east_bay = ['Alameda', 'Oakland', 'Fremont', 'Hayward', 'Pleasanton',
            'Berkeley', 'San Leandro', 'Livermore', 'Dublin', 'Castro Valley',
            'Union City', 'Newark', 'Emeryville', 'San Lorenzo', 'Albany',
            'Piedmont', 'Sunol', 'Cherryland', 'Ashland', 'Fairview',
            'Martinez', 'Concord', 'Antioch', 'Walnut Creek', 'Richmond',
            'Brentwood', 'Pittsburg', 'Pleasant Hill', 'San Ramon', 'Danville',
            'San Pablo', 'Oakley', 'El Cerrito', 'Lafayette', 'Orinda',
            'Hercules', 'Pinole', 'Moraga', 'El Sobrante', 'Alamo',
            'Clayton', 'Bay Point', 'Discovery Bay', 'Rodeo', 'Contra Costa Centre',
            'Crockett', 'North Richmond', 'Byron', 'Diablo', 'Blackhawk',
            'Knightsen', 'Bethel Island', 'Pacheco', 'Kensington', 'Port Costa',
            'East Richmond Heights', 'Alhambra Valley', 'Tara Hills', 'Vine Hill', 'Clyde',
            'Rollingwood']

south_bay = ['Santa Clara', 'San Jose', 'Sunnyvale', 'Palo Alto', 'Mountain View',
             'Milpitas', 'Cupertino', 'Gilroy', 'Morgan Hill', 'Los Gatos',
             'Campbell', 'Los Altos', 'Saratoga', 'Stanford', 'San Martin',
             'Los Altos Hills', 'Monte Sereno', 'Alum Rock', 'Cambrian Park', 'Fruitdale',
             'East Foothills', 'West Santa Clara', 'Loyola']

peninsula = ['San Francisco', 'San Bruno', 'San Mateo', 'Redwood City', 'Burlingame',
             'South San Francisco', 'Foster City', 'Daly City', 'Half Moon Bay', 'San Carlos',
             'Menlo Park', 'Millbrae', 'Pacifica', 'Belmont', 'East Palo Alto',
             'Atherton', 'Hillsborough', 'Woodside', 'Portola Valley', 'Colma',
             'Pescadero', 'Montara', 'Brisbane', 'El Granada', 'La Honda',
             'Moss Beach', 'North Fair Oaks', 'San Gregorio', 'Loma Mar', 'Emerald Hills',
             'West Menlo Park', 'Broadmoor']

north_bay = ['San Rafael', 'Novato', 'Mill Valley', 'Sausalito', 'Larkspur',
             'Corte Madera', 'San Anselmo', 'Marin City', 'Fairfax', 'Stinson Beach',
             'Kentfield', 'Bolinas', 'Ross', 'Muir Beach', 'Strawberry',
             'Point Reyes Station', 'Inverness', 'Tomales', 'San Geronimo', 'Nicasio',
             'Woodacre', 'Dillon Beach', 'Marshall', 'Santa Venetia', 'Woodville',
             'Sonoma', 'Santa Rosa', 'Petaluma', 'Healdsburg', 'Rohnert Park',
             'Sebastopol', 'Bodega Bay', 'Windsor', 'Guerneville', 'Cloverdale',
             'Cotati', 'Forestville', 'Kenwood', 'Geyserville', 'Occidental',
             'Jenner', 'Sea Ranch', 'Monte Rio', 'Boyes Hot Springs', 'Graton',
             'Penngrove', 'Bodega', 'El Verano', 'Duncans Mills', 'Valley Ford',
             'Rio Nido', 'Carmet', 'Temelec', 'Sereno del Mar', 'Timber Cove',
             'Salmon Creek', 'Annapolis', 'Fulton', 'Eldridge', 'Bloomfield',
             'Napa', 'Yountville', 'Calistoga', 'American Canyon', 'Rutherford',
             'Oakville', 'Angwin', 'Moskowite Corner', 'Deer Park', 'Fairfield',
             'Vacaville', 'Vallejo', 'Suisun City', 'Benicia', 'Dixon',
             'Green Valley', 'Birds Landing', 'Elmira', 'Rockville', 'Allendale']